export type ArchNode = {
  id: string
  n: string
  title: string
  role: string
  llm: string
  purpose: string
  reads: string[]
  writes: string[]
  work: string[]
  formula?: string
  why?: string
  example: string[]
  next: string
}

export const STATE_KEYS = [
  { id: 'question', label: 'question', from: 'planner' },
  { id: 'intent', label: 'intent + queries', from: 'planner' },
  { id: 'articles', label: 'articles', from: 'scout' },
  { id: 'topics', label: 'topics + entities', from: 'topic_analyst' },
  { id: 'momentum', label: 'momentum', from: 'momentum_analyst' },
  { id: 'coverage', label: 'coverage', from: 'librarian' },
  { id: 'graph', label: 'graph snapshot', from: 'graph_curator' },
  { id: 'gaps', label: 'gaps + actions', from: 'gap_analyst' },
  { id: 'answer', label: 'answer', from: 'synthesizer' },
  { id: 'critique', label: 'critic notes', from: 'critic' },
]

export const ARCH_ORDER = [
  'frontend',
  'api',
  'planner',
  'scout',
  'topic_analyst',
  'momentum_analyst',
  'librarian',
  'graph_curator',
  'gap_analyst',
  'synthesizer',
  'critic',
  'storage',
]

export const ARCH_NODES: Record<string, ArchNode> = {
  frontend: {
    id: 'frontend',
    n: '00',
    title: 'React workspace',
    role: 'UI',
    llm: 'No',
    purpose: 'The analyst picks the job and types the question. Market scan or Ask the library is locked here so the Planner cannot send a library question to the web.',
    reads: ['Typed question (2–500 characters)', 'Selected mode', 'fresh-search flag'],
    writes: ['GET /api/ask/stream with q, intent, refresh', 'Renders SSE agent cards and the final result'],
    work: [
      'Research studio is the workbench. Opportunities is the saved portfolio map.',
      'Knowledge map shows this scan: news names, topics, our notes.',
      'Previous runs replay SQLite. No live Tavily or Gemini.',
    ],
    example: [
      'Mode: Market scan',
      'Question: What topics related to AI in healthcare have surged recently?',
    ],
    next: 'FastAPI opens a worker and streams every agent event.',
  },
  api: {
    id: 'api',
    n: '00b',
    title: 'FastAPI + SSE',
    role: 'HTTP',
    llm: 'No',
    purpose: 'One request boundary. Validates the question, runs LangGraph, pushes real trace events. Not a fake progress animation.',
    reads: ['q, intent, refresh from the browser'],
    writes: ['trace / result / done events over SSE', 'SQLite run snapshot when the graph finishes'],
    work: [
      'Forced valid intents skip LLM classification.',
      'Pause updates closes the browser stream. It does not cancel the backend.',
    ],
    example: ['GET /api/ask/stream?q=AI+in+healthcare&intent=market_scan'],
    next: 'LangGraph Planner is node 1 on the shared state.',
  },
  planner: {
    id: 'planner',
    n: '01',
    title: 'Planner',
    role: 'Router',
    llm: 'Only Auto route. Demo tab = code.',
    purpose: 'Choose a workflow. A library question must not trigger web search. A market scan must not answer from memory.',
    reads: ['Original question', 'forced_intent from the UI tab'],
    writes: ['intent', 'research_area', 'queries', 'reasoning', 'plan'],
    work: [
      'Keeps the original question untouched for the final answer.',
      'Derives a shorter search subject for Scout.',
      'Forced Market scan: three queries in code — the subject, emerging trends, regulation governance.',
    ],
    formula: 'forced_intent in {market_scan, library_qa}  →  skip Gemini classify',
    why: 'The model can mis-route. The tab is the source of truth in the interview.',
    example: [
      'Question stays: “What topics related to AI in healthcare have surged recently?”',
      'research_area: “AI in healthcare”',
      'queries: AI in healthcare · emerging trends · regulation governance',
    ],
    next: 'Scout reads queries. Every later agent still sees question.',
  },
  scout: {
    id: 'scout',
    n: '02',
    title: 'Signal Scout',
    role: 'External search',
    llm: 'No. Tavily + cache only.',
    purpose: 'Collect recent public articles. Scout does not name topics.',
    reads: ['queries', 'research_area', 'refresh flag'],
    writes: ['articles[]', 'scout_stats', 'signal_source'],
    work: [
      'Up to 8 Tavily hits per query, last 45 days.',
      'De-duplicate by URL across the three queries.',
      'Three counts: per-query, raw total, unique URLs.',
    ],
    formula: '8+6+7 raw = 21   →   unique URLs = 17 if 4 duplicates',
    why: 'The same story appears under different queries. Counting raw rows would inflate demand.',
    example: [
      'A1 outlet-a · 12 Sep · clinical AI oversight committees',
      'A2–A6 more governance / hospital AI excerpts',
      'Topic Analyst sees title, snippet, date, domain — not full HTML.',
    ],
    next: 'Topic Analyst reads articles. Original question is still in state.',
  },
  topic_analyst: {
    id: 'topic_analyst',
    n: '03',
    title: 'Topic Analyst',
    role: 'LLM + embeddings',
    llm: 'Yes. Extract in batches of 6, then one naming call.',
    purpose: 'Many wordings, one durable topic. Article counts must stay with the merged group — we do not re-search the clean name.',
    reads: ['articles (title, snippet, date, domain)', 'research_area'],
    writes: ['topics[]', 'topic_objects', 'aliases', 'entities', 'normalisation counts'],
    work: [
      '3A Extract: Gemini, 6 articles per call, 1–3 themes + entities + a news driver.',
      '3B Flatten phrases and keep which article said them.',
      '3C Clean strings. 3D Embed and cluster at cosine ≥ 0.93.',
      '3E One naming call for canonical labels. 3F Map members back to URLs and entities.',
    ],
    formula: 'extract batches  →  embed + cluster (≥ 0.93)  →  one naming LLM',
    why: 'If Scout searched again on “Clinical AI Governance”, alias merging would be thrown away. Mentions stay on the cluster.',
    example: [
      '“FDA hospital AI rules” + “clinical AI oversight” → Clinical AI Governance',
      'Entity on that topic: Example Hospital',
      '12 articles / 2 phrases each can become 3 canonical topics. Articles stay separate evidence.',
    ],
    next: 'Attention reads mention_count, source_count, last_seen on each topic.',
  },
  momentum_analyst: {
    id: 'momentum_analyst',
    n: '04',
    title: 'Attention Analyst',
    role: 'Python arithmetic',
    llm: 'No.',
    purpose: 'Turn this news sample into a 0–1 attention score. Not client demand. Not a year-on-year surge.',
    reads: ['mention_count (unique URLs)', 'source_count (distinct domains)', 'last_seen'],
    writes: ['momentum', 'recency_days', 'growth_pct = null on the live path', 'source: derived'],
    work: [
      'Counts come from Agent 3’s mapping. This node does not search again.',
      'Empty historical series → derived path. No GDELT volume line.',
      'Three articles from one site = 3 mentions, 1 outlet.',
    ],
    formula: 'breadth = min(1, 0.7×sites/6 + 0.3×min(articles,12)/12)\nrecency = exp(−days/30)\nattention = 0.7×breadth + 0.3×recency',
    why: 'Breadth kills one-outlet spam. Recency kills last month’s spike. Weights are prototype, not learned Gartner numbers. Multiply into gap later so a quiet empty topic is not first.',
    example: [
      'AI Governance teaching: 5 articles, 4 sites, 4 days old',
      'breadth = 0.7×4/6 + 0.3×5/12 = 0.5917',
      'recency = exp(−4/30) = 0.8752',
      'momentum = 0.7×0.5917 + 0.3×0.8752 = 0.6767',
    ],
    next: 'Librarian searches the library using label + description. It does not use momentum to judge relevance.',
  },
  librarian: {
    id: 'librarian',
    n: '05',
    title: 'Librarian · coverage',
    role: 'RAG + LLM judge + Python score',
    llm: 'Yes for verdicts (covers / partial / tangential). No for the 0–1 number.',
    purpose: 'Does our shelf actually answer this topic today? Radiology is not governance.',
    reads: ['Each topic label + description', 'FAISS index from setup'],
    writes: ['coverage[slug]', 'matched_docs with verdict and age', 'coverage_score on the topic'],
    work: [
      'Retrieve up to 50 chunks (one report can fill many neighbour slots).',
      'Drop Syndicated Archive. Best chunk per document. Keep ≤10 with similarity ≥ 0.62.',
      'One Gemini judge call per topic on those candidates (first 420 characters).',
      'Keep ≤5 covers/partial. Python ages them and mixes depth + best note.',
    ],
    formula: 'usable = verdict × (0.25 + 0.75 × freshness)\ncoverage = 0.6 × min(1, Σ usable / 5) + 0.4 × max(usable)\ncovers=1  partial=0.5  tangential=0',
    why: 'FAISS only knows “healthcare near healthcare.” Without the judge, every hospital-AI note would look like coverage. Age floor 0.25 means an old playbook is not nothing, but cannot look current. Depth saturates at 5 real notes.',
    example: [
      'Topic: Clinical AI Governance',
      'RN-9001 covers, 500 days old → usable = 0.25',
      'RN-9002 diagnostic accuracy → tangential → 0',
      'RN-9003 ambient docs → tangential → 0',
      'coverage = 0.6×(0.25/5) + 0.4×0.25 = 0.13',
    ],
    next: 'Graph uses accepted docs. Gap uses momentum × (1 − coverage).',
  },
  graph_curator: {
    id: 'graph_curator',
    n: '06',
    title: 'Graph Curator',
    role: 'Python NetworkX',
    llm: 'No generative call. Embeddings only for topic adjacency.',
    purpose: 'Draw links already sitting in state. Left = news names. Middle = topics. Right = our notes.',
    reads: ['topic_objects.entities from Agent 3', 'coverage.matched_docs from Agent 5'],
    writes: ['graph summary', 'query snapshot (≤300 nodes)', 'SQLite kg_nodes / kg_edges'],
    work: [
      'mentions: topic → company / regulator / tool',
      'covered_by: topic → accepted note (≤4 per topic)',
      'published_in: note → practice area',
      'adjacent_to: topic–topic cosine ≥ 0.62',
    ],
    formula: 'no extra LLM   ·   adjacent if cosine(label+description) ≥ 0.62',
    why: 'So a director can see in one hop: extend RN-9001 rather than start from nothing. Gap Analyst does not use graph counts.',
    example: [
      'Clinical AI Governance —mentions→ Example Hospital',
      'Clinical AI Governance —covered_by→ RN-9001',
      'RN-9001 —published_in→ Healthcare & Life Sciences',
    ],
    next: 'Gap Analyst ignores the graph and reads momentum + coverage.',
  },
  gap_analyst: {
    id: 'gap_analyst',
    n: '07',
    title: 'Gap Analyst',
    role: 'Python rules',
    llm: 'No.',
    purpose: 'Rank the mismatch. Assign commission / refresh / maintain / watch.',
    reads: ['topic.momentum from Agent 4', 'coverage_score and staleness from Agent 5'],
    writes: ['gaps[]', 'priority', 'quadrant', 'rationale', 'portfolio summary'],
    work: [
      'gap = attention × (1 − coverage). Multiply so both must be true.',
      'If attention ≥ 0.50, a note exists, newest > 300 days, coverage < 0.70 → refresh beats commission.',
      'Sort by gap. Store in SQLite. Opportunities reads these rows.',
    ],
    formula: 'gap = attention × (1 − coverage)\nHot 0.69 × empty-ish 0.87 ≈ 0.60',
    why: 'Subtracting would make a quiet empty topic look as urgent as a hot empty one. The product definition of an opportunity is hot market times empty shelf.',
    example: [
      'Clinical AI Governance: attention 0.6942, coverage 0.13, age 500 days',
      'gap ≈ 0.6040  ·  CRITICAL  ·  quadrant refresh',
      'Rationale: validate the old playbook before commissioning a new paper.',
    ],
    next: 'Synthesizer writes sentences from this table. Actions stay Python.',
  },
  synthesizer: {
    id: 'synthesizer',
    n: '08',
    title: 'Synthesizer',
    role: 'LLM writer',
    llm: 'Yes. Fallback template if Gemini fails.',
    purpose: 'Explain the computed findings to a research director in 60 seconds.',
    reads: ['question', 'top gaps with IDs and ages', 'article / outlet counts'],
    writes: ['answer', 'executive_summary', 'recommendations (from Python)'],
    work: [
      'Prompt cites the supplied numbers only.',
      'Recommendation chips = f(quadrant) in code: commission / refresh / maintain / review / monitor.',
      'Library QA skips this node — the answer already exists.',
    ],
    formula: 'narrative = Gemini(analytics)    actions = Python(quadrant)',
    why: 'The model may explain. It may not silently change the ranking.',
    example: [
      '“Clinical AI Governance attention 0.69, coverage 0.13, gap 0.60. The matched note is 500 days old — refresh it. Sampled news, simulated library.”',
    ],
    next: 'Critic compares that paragraph to the same numbers.',
  },
  critic: {
    id: 'critic',
    n: '09',
    title: 'Critic',
    role: 'LLM audit',
    llm: 'Yes. Skips on library QA (groundedness already ran).',
    purpose: 'Flag a summary that invents or overstates a number.',
    reads: ['executive answer', 'gap analytics (momentum, coverage, gap, priority)'],
    writes: ['consistent', 'critique_issues[]', 'confidence'],
    work: [
      'Separate structured call. Not a human review and not a different model by default.',
      'Does not re-read the news or the library.',
    ],
    formula: 'if summary contradicts analytics → issues[] shown in the UI',
    why: 'Synthesis is the one place an LLM could quietly over-claim. The audit is visible, not hidden.',
    example: ['{ consistent: true, issues: [], confidence: 0.92 }', 'If it said coverage is high while 0.13, that issue is listed.'],
    next: 'SQLite stores the full snapshot. UI shows the result and can replay it.',
  },
  storage: {
    id: 'storage',
    n: '10',
    title: 'SQLite snapshot',
    role: 'Memory',
    llm: 'No.',
    purpose: 'The demo stays usable when Gemini is slow. Replay is labelled as saved, not live.',
    reads: ['Final serialisable state, trace, graph snapshot, telemetry'],
    writes: ['runs.result_json', 'topics, coverage, gaps, signals, kg_*'],
    work: [
      'GET /api/runs/{id}/result returns the snapshot with no Tavily or Gemini.',
      'Knowledge map uses this run’s snapshot so a later scan cannot silently replace it.',
    ],
    example: ['Saved run #7 · AI in healthcare · 9 nodes · 8 connections'],
    next: 'Analyst decides. The system proposes research; it does not write the paper.',
  },
  librarian_rag: {
    id: 'librarian_rag',
    n: 'QA',
    title: 'Librarian · Ask the library',
    role: 'RAG QA',
    llm: 'Yes: answer + groundedness. Synthesizer and Critic skip.',
    purpose: 'Answer a client question only from our notes, with [RN-####] citations.',
    reads: ['Original question', 'FAISS index'],
    writes: ['answer', 'citations', 'hits', 'groundedness'],
    work: [
      'Embed the question. Search. Drop archive. ≤2 chunks per document, about 6 kept.',
      'Gemini answers from those extracts only. Unknown IDs are stripped.',
      'Second pass scores whether claims are supported.',
    ],
    formula: 'question → passages → cited answer → groundedness',
    why: 'Uncited advice is worthless here. Empty retrieval must abstain, not invent.',
    example: [
      'Q: What governance practices does our internal research recommend for clinical AI?',
      'Hit RN-9001 score 0.82',
      'A: Assign clinical and technical owners and document model review. [RN-9001]',
    ],
    next: 'UI shows the answer, citations, extracts and support estimate.',
  },
}

export const SHARED_STATE_STORY = [
  'Planner: question + intent + queries',
  'Scout: previous + articles + scout_stats',
  'Topic Analyst: previous + topics + topic_objects',
  'Attention: same topics now have momentum',
  'Coverage: previous + coverage map',
  'Graph: previous + snapshot; also saved',
  'Gap: previous + gaps + portfolio',
  'Synthesizer: previous + answer + recommendations',
  'Critic: previous + verdict + issues',
]
